### ISSUE TITLE
No caso do Bradesco, o campo dataPagamento deve guardar a data e hora

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/retorno-boleto#1]
O arquivo do bradesco já virá com a data e hora no campo dataPagamento.
O seu código abaixo está considerando que só existe a data e está incluindo a hora como 00:00 para todas as linhas neste campo.

https://github.com/trasherdave/retorno-boleto/blob/cf191bc9055b60cfe24d5f44fdb9fc8d36c91940/src/main/java/com/david/retorno/boleto/LeituraRetornoBradesco.java#L37

O que deveria é usar o tipo LocalDateTime:

```java
boleto.setDataPagamento(LocalDateTime.parse(vetor[5], FORMATO_DATA_HORA));   
```

**Comment by trasherdave** [comment]
Entendido! muito obrigado!
